spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
