version: '3.8'
services:
  config-server:
    image: image-config-service
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - eureka-network

  eureka-server:
    image: image-eureka-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  microservice1:
    image: image-car-service
    container_name: car-service
    ports:
      - "9090:9090"
    networks:
      - eureka-network
    depends_on:
      - config-server
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888


  gateway:
    image: image-gateway-service
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

networks:
  eureka-network:
    driver: bridge


#
#  microservice2:
#    image: microservice2-image
#    container_name: microservice2
#    networks:
#      - eureka-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
#
#  microservice3:
#    image: microservice3-image
#    container_name: microservice3
#    networks:
#      - eureka-network
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888


