#spring:
#  application:
#    name: user-service
#  config:
#    import: optional:configserver:http://localhost:8888
spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888