spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_service
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: create

    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        retries: 1
        properties:
          spring.json.type.mapping: BookingNotification:app.vercel.mohammedelyousfi.booking_service.domain.model.BookingNotification

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator/inventory