spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v1/cars/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**

  main:
    web-application-type: reactive

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:9090/realms/spring-boot-dev
#        registration:
#          spring-cloud-gateway-client:
#            client-id: spring-cloud-gateway
#            client-secret: WQk4Oyqvfp5Ghsf0OINTvmBKdnar8vZR
#            provider: keycloak
#            scope: openid
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8080

# Keycloak Configuration (commented out)


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
