version: '3.8'

services:
  mongo-server:
    image: mongo:4.4.10
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongodb_network

  mongo-client:
    image: mongo-express:0.54.0
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "8081:8081"
    networks:
      - mongodb_network

volumes:
  mongo_data:

networks:
  mongodb_network:
